# Generated by Django 5.1.3 on 2024-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
